export const DELETE_COMMENT = 'DELETE_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const SET_CURRENT_COMMENT = 'SET_CURRENT_COMMENT'
export const LOG_EDITED_COMMENT = 'LOG_EDITED_COMMENT'

