export const DELETE_COMMENT = 'DELETE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const SET_CURRENT_COMMENT = 'SET_CURRENT_COMMENT'
export const LOG_EDITED_COMMENT = 'LOG_EDITED_COMMENT'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const REQUEST_COMMENTS = 'REQUEST_COMMENTS'

